---
version: '3.3'
services:
  postgis:
    image: postgis/postgis:15-3.3-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgrespassword
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
